import Head from "next/head"
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import { Button } from "antd"

export default function Home() {
  const { data: session } = useSession()

  return (
    <div>
      <Head>
        <title>Next.js Twitter Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Content goes here
      {!session && <Button onClick={() => signIn()}>Sign In</Button>}
      {session && <Button onClick={() => signOut()}>Sign Out</Button>}
      {session && (
        <div>
          <p>{ JSON.stringify(session.user) }</p>
          <h2>{ session.user.name }</h2>
          <img src={session.user.image} />
        </div>
      )}
    </div>
  )
}
