import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {
  const { data: session } = useSession()

  return (
    <div>
      <Head>
        <title>Next.js Twitter Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Content goes here
      {!session && <button onClick={() => signIn()}>Sign In</button>}
      {session && <button onClick={() => signOut()}>Sign Out</button>}
      {session && <p>{ JSON.stringify(session.user) }</p>}
    </div>
  )
}
